version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pretty-bytes
    versions:
    - 5.5.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: imagemin-pngquant
    versions:
    - 9.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: fs-extra
    versions:
    - 9.0.1
